val set1 = Set(1,2,3)
val set2 = Set(1,2,3) + 4
val set3 = set2 - 4
println("contains sample")
println(set1(1))
println(set1(4))
println("add and sub sample")
println(set1 ++ set2 == set2)
println(set2 -- set1 == Set(1))
println("subset sample")
println(set1 subsetOf set2)
println(set2 subsetOf set1)
println(set1 subsetOf set1)
println("empty sample")
println(Set().empty)
val oddSet = Set(1,3,5,7,9)
val primeSet = Set(2,3,5,7,11)
println("mul group sample")
println(oddSet & primeSet)
println("add group sample")
println(oddSet | primeSet)
println("sub group sample")
println(oddSet &~ primeSet)
println(oddSet -- primeSet)
println(primeSet &~ oddSet)
println(primeSet -- oddSet)

val mutableSet1 = scala.collection.mutable.Set(1)
mutableSet1 += 2
println(mutableSet1)
mutableSet1 += (2,3,4)
println(mutableSet1)
